"""add user_id to 
  watchlist

Revision ID: ed7cf509f6e1
Revises: f810b7c4281d
Create Date: 2026-05-25 23:12:31.552710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ed7cf509f6e1'
down_revision: Union[str, None] = 'f810b7c4281d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('watchlist_asset_id_key'), 'watchlist', type_='unique')
    op.create_unique_constraint(None, 'watchlist', ['user_id', 'asset_id'])
    op.create_foreign_key(None, 'watchlist', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'watchlist', type_='foreignkey')
    op.drop_constraint(None, 'watchlist', type_='unique')
    op.create_unique_constraint(op.f('watchlist_asset_id_key'), 'watchlist', ['asset_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('watchlist', 'user_id')
    # ### end Alembic commands ###
